### ISSUE TITLE
Rendering docker-compose files with short healthcheck config Fails

### ISSUE THREAD

**Issue by ezodude** [appvia/tako#194]
The K8s converter expects all `healthcheck` values in the docker-compose file to be available. But panics if some attributes are missing.

For refrenece See: `converter/kubernetes/project_service.go#healthcheck()`.

This won't always be the case, as you may just have the `test` attribute.

E.g. This is **valid** config,
```
version: '3.7'
services:
  mysql:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    healthcheck:
      test: ["CMD", "curl", "localhost:80/healthy"]
volumes:
  db_data:
```

`kev` captures all the `healthcheck` values using labels - perhaps these can be used to fill in the blanks.
