### ISSUE TITLE
Reconcile: environment variables issue

### ISSUE THREAD

**Issue by marcinc** [appvia/tako#205]
With service in source compose having environment specified `BAR: FOO`:

```
version: '3.7'
services:
  test:
    image: gcr.io/google-containers/busybox:latest
    restart: always
    environment:
      BAR: FOO
```

When I specify an override to this env variable in my dev overlay compose file:

```
test:
  labels:
    ...
  environment:
    BAR: BAZ
``` 

then run `render` again I see:

```
✓ Reconciling environment [dev]
 → service [test], env var [BAR] deleted
```

and as a result my override to environment variable disappears from dev env entirely.
