### ISSUE TITLE
Add PortForward section to skaffold config for externally built containers

### ISSUE THREAD

**Issue by marcinc** [appvia/tako#378]
Currently `skaffold dev` doesn't tail logs or port-forwards services that aren't build by skaffold. See relevant issue: https://github.com/GoogleContainerTools/skaffold/issues/5067

Alternative solution would be to explicitly inject (and reconcile) `portForward` config section for relevant services, e.g.:

```yaml
portForward:
  - resourceType: Service
    resourceName: wordpress
    namespace: wp
    port: 8080
    localPort: 8080
```
