### ISSUE TITLE
Incorrect Workload Type is rendered

### ISSUE THREAD

**Issue by ezodude** [appvia/tako#501]
Expected a `Statefulset` to be rendered from the `db-test` service but instead a `Deployment` was rendered.

## How to reproduce the bug

Checkout the `labels-to-extension` branch and use the source docker-compose file below.

- Run `make`.
- Run `kev init`.
- Run `kev render`, it produces: `k8s/dev/db-test-deployment.yaml`

__!!This is incorrect!!__ it should produce: `k8s/dev/db-test-statefulset.yaml`

__Source docker-compose file__

```yaml
version: '3.8'
services:

  db-test:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - "3306"

  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    depends_on:
      - db-test
    environment:
      WORDPRESS_DB_HOST: db-test:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data:
```
