### ISSUE TITLE
Fix config compiler to take attributes with numeric values into account

### ISSUE THREAD

**Issue by marcinc** [appvia/tako#60]
Noticed that `kev build` would omit attributes with numeric values in compiled configuration, unless they are provided  explicitly in environment specific overrides.

Example:

* Base config
```yaml
backend:
  workload:
    type: Deployment
    replicas: 1
```

* Env specific override
```yaml
backend: {}
```

Resultant compiled configuration
```yaml
backend:
  workload:
    type: Deployment
```
 
Example 2:

When env config override defines that numeric attribute it'll be taken into account:

Env override:
```yaml
backend:
   replicas: 5
```

will produce resultant:
```yaml
backend:
  workload:
    type: Deployment
    replicas: 5
```
